version: '3.8'

services:
  # Сервис для PostgreSQL
  db:
    image: postgres:13
    networks:
      - network
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
  backend:
    build: .
    container_name: go_backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - network
volumes:
  postgres_data:
    driver: local
networks:
  network:
    driver: bridge